storagePath: ./var
peers:
  - wallet.burst.cryptoguru.org
  - 195.201.124.43
  - 138.201.159.96
  - 195.201.116.237
  - 138.201.159.82
  - 50-50-pool.burst.cryptoguru.org
  - 0-100-pool.burst.cryptoguru.org
  - 100-0-pool.burst.cryptoguru.org
  - burst-a.bayernport.com
internetProtocols:
  - v4
